name: Win/Mac/Linux

on:
  push:
    branches-ignore:
      - gh-pages
      - fatdrvce-rewrite
  pull_request:
    branches:
      - master

env:
  AUTOTESTER_LIBS_GROUP: ${{github.workspace}}/toolchain/clibs.8xg
  AUTOTESTER_PATH: ${{github.workspace}}/CEmu/tests/autotester
  AUTOTESTER_ROM: ${{github.workspace}}/secrets/84pce_515_53.rom
  CEDEV: ${{github.workspace}}/CEdev
  CEDEV_BIN: ${{github.workspace}}/CEdev/bin
  CEDEV_EXAMPLES: ${{github.workspace}}/CEdev/examples
  CEMU_PATH: ${{github.workspace}}/CEmu
  FASMG_DOMAIN: https://flatassembler.net
  FASMG_PATH: ${{github.workspace}}/fasmg
  HOST_DOMAIN: https://jacobly.com
  SECRETS_PATH: ${{github.workspace}}/secrets
  TOOLCHAIN_PATH: ${{github.workspace}}/toolchain

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        runs-on: [ubuntu, macos, windows]
        include:
          - nul: /dev/null
          - runs-on: macos
            fasmg: /source/macos/x64/fasmg
          - runs-on: windows
            fasmg: /fasmg.exe
            env: "env:"
            exe: .exe
            nul: nul
          - runs-on: ubuntu
            fasmg: /fasmg.x64
    runs-on: ${{matrix.runs-on}}-latest
    steps:
      - name: Prepare Build Environment
        run: cmake -E echo >> $${{matrix.env}}GITHUB_PATH ${{env.CEDEV_BIN}}

      - name: Download ez80-clang
        id: ez80-clang
        uses: carlosperate/download-file-action@v1.0.3
        with:
          file-url: ${{env.HOST_DOMAIN}}/artifact?repo=llvm-project&branch=z80&file=ez80-clang${{matrix.exe}}-${{runner.os}}Release
      - name: Extract ez80-clang
        uses: DuckSoft/extract-7z-action@v1.0
        with:
          pathSource: ${{steps.ez80-clang.outputs.file-path}}
          pathTarget: ${{env.CEDEV_BIN}}

      - name: Download Fasmg Download Page
        id: fasmg-download
        uses: carlosperate/download-file-action@v1.0.3
        with:
          file-url: ${{env.FASMG_DOMAIN}}/download.php
      - name: Parse Fasmg Download Page
        id: fasmg-url
        uses: QwerMike/xpath-action@v1
        with:
          filename: ${{steps.fasmg-download.outputs.file-path}}
          expression: //a[starts-with(text(),"flat assembler g ")]/@href
      - name: Extract Fasmg Url
        run: cmake -E echo >> $${{matrix.env}}GITHUB_ENV ${{steps.fasmg-url.outputs.result}}
      - name: Download Fasmg
        id: fasmg
        uses: carlosperate/download-file-action@v1.0.3
        with:
          file-url: ${{env.FASMG_DOMAIN}}/${{env.href}}
      - name: Extract Fasmg
        uses: DuckSoft/extract-7z-action@v1.0
        with:
          pathSource: ${{steps.fasmg.outputs.file-path}}
          pathTarget: ${{env.FASMG_PATH}}
      - name: Setup Fasmg
        run: cmake -E copy fasmg${{matrix.fasmg}} ${{env.CEDEV_BIN}}/fasmg${{matrix.exe}}

      - name: Make Binaries Executable
        if: runner.os != 'Windows'
        run: chmod +x ${{env.CEDEV_BIN}}/*
      - name: Test Build Dependencies
        run: |
          ez80-clang --version
          fasmg ${{matrix.nul}} ${{matrix.nul}}

      - name: Checkout Toolchain
        uses: actions/checkout@v2.3.4
        with:
          path: ${{env.TOOLCHAIN_PATH}}
          submodules: recursive
          persist-credentials: false
      - name: Build Toolchain
        run: make -j4 -C ${{env.TOOLCHAIN_PATH}} V=1
      - name: Install Toolchain
        env:
          PREFIX: ${{github.workspace}}
        run: make -j4 -C ${{env.TOOLCHAIN_PATH}} install release release-libs V=1

      - name: Upload CEdev
        uses: actions/upload-artifact@v2
        with:
          name: CEdev-${{runner.os}}
          path: ${{env.CEDEV}}
      - name: Upload Libraries
        uses: actions/upload-artifact@v2
        with:
          name: clibs
          path: ${{env.AUTOTESTER_LIBS_GROUP}}

  test:
    needs: build
    environment: Autotester
    strategy:
      fail-fast: false
      matrix:
        runs-on: [ubuntu, macos, windows]
        include:
          - runs-on: windows
            env: "env:"
    runs-on: ${{matrix.runs-on}}-latest
    steps:
      - name: Prepare Test Environment
        run: cmake -E echo >> $${{matrix.env}}GITHUB_PATH ${{env.CEDEV_BIN}}

      - name: Download CEdev
        uses: actions/download-artifact@v2
        with:
          name: CEdev-${{runner.os}}
          path: ${{env.CEDEV}}

      - name: Make Binaries Executable
        if: runner.os != 'Windows'
        run: chmod +x ${{env.CEDEV_BIN}}/*
      - name: Build Examples
        run: make -j4 -C ${{env.CEDEV_EXAMPLES}} V=1

      - name: Checkout CEmu
        uses: actions/checkout@v2.3.4
        with:
          repository: ${{github.repository_owner}}/CEmu
          ref: latest-stable
          path: ${{env.CEMU_PATH}}
          persist-credentials: false
      - name: Build CEmu
        run: make -j4 -C ${{env.CEMU_PATH}}/core
      - name: Build Autotester CLI
        run: make -j4 -C ${{env.AUTOTESTER_PATH}}

      - name: Download Secrets
        id: download-secrets
        uses: carlosperate/download-file-action@v1.0.3
        with:
          file-url: ${{env.HOST_DOMAIN}}/${{github.repository_owner}}/secrets
          location: ${{env.SECRETS_PATH}}
      - name: Decrypt Secrets
        env:
          KEY: ${{secrets.SYMMETRIC_KEY_256}}
        run: openssl enc -d -aes-256-cbc -iv a581c6a54a2b51143fecad6794deb32a -K "$${{matrix.env}}KEY" -in ${{steps.download-secrets.outputs.file-path}} -out ${{env.SECRETS_PATH}}/secrets.7z
      - name: Extract Secrets
        uses: DuckSoft/extract-7z-action@v1.0
        with:
          pathSource: ${{env.SECRETS_PATH}}/secrets.7z
          pathTarget: ${{env.SECRETS_PATH}}

      - name: Download Libraries
        uses: actions/download-artifact@v2
        with:
          name: clibs
          path: ${{env.TOOLCHAIN_PATH}}
      - name: Test Examples
        if: runner.os != 'Windows'
        run: |
          failed=0
          find ${{env.CEDEV_EXAMPLES}} -name autotest.json -print0 | while read -d '' test; do
            cmake -E echo "Launching autotester on $test"
            ${{env.AUTOTESTER_PATH}}/autotester "$test"
            cmake -E true $((failed += $?))
          done
          cmake -E echo "$failed tests failed"
          exit $failed
      - name: Test Examples
        if: runner.os == 'Windows'
        run: |
          $failed = 0
          foreach ($test in get-childitem "${{env.CEDEV_EXAMPLES}}" -recurse -include autotest.json) {
            cmake -E echo "Launching autotester on $test"
            ${{env.AUTOTESTER_PATH}}\autotester.exe "$test"
            $failed += $lastexitcode
          }
          cmake -E echo "$failed tests failed"
          exit $failed

      - name: Remove Secrets
        if: always()
        run: cmake -E rm -rf ${{env.SECRETS_PATH}}

  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Install Documentation Dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get install -y doxygen
          pip install docutils==0.16
          pip install sphinx==3.2.1 sphinx_rtd_theme breathe
          cmake -E echo >> $${{matrix.env}}GITHUB_PATH $${{matrix.env}}HOME/.local/bin

      - name: Checkout Toolchain
        uses: actions/checkout@v2.3.4
        with:
          path: ${{env.TOOLCHAIN_PATH}}
          persist-credentials: false

      - name: Build Website Documentation
        run: make -C ${{env.TOOLCHAIN_PATH}}/docs html
      - name: Disable Jekyll
        run: cmake -E touch ${{env.TOOLCHAIN_PATH}}/docs/build/html/.nojekyll

      - name: Upload Website Documentation
        if: github.ref == 'refs/heads/master'
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          BRANCH: gh-pages
          FOLDER: ${{env.TOOLCHAIN_PATH}}/docs/build/html
          CLEAN: true
